### PR TITLE
Added Many things in the website

### PR DESCRIPTION
**Pull request by kishanlalchoudhary**
1. Centered-logo
2. Navigation bar with hover effect
3. Hero section
4. Grid-layout for listing products (responsive for all types of screen)
5. Button hover effect
6. Responisve design
7. Pls accept my PR if you like under hactoberfest2022

### CODE REVIEW

**Comment by kishanlalchoudhary** [comment]
you are mainter in hactoberfest right

**Comment by kishanlalchoudhary** [comment]
pls add hactoberfesttag

**Comment by kishanlalchoudhary** [comment]
pls hactoberfest-accepted tag

**Comment by kishanlalchoudhary** [comment]
Pls merge my pr

**Comment by kishanlalchoudhary** [comment]
Why invalid

**Comment by kishanlalchoudhary** [comment]
Can I come contribute in another feature

**Comment by kishanlalchoudhary** [comment]
I wrote approx 180 lines of code pls merge it

**Comment by areebhammad** [comment]
Sorry, I have got some better PR'. But you can work on the new issue that I have mentioned.

**Pull request closed without merging**
